#!/usr/bin/env bash

#-----------------------------------------------------------------------------
ROOT_DIR="$(dirname "$(perl -e 'use Cwd "abs_path"; \
                                print abs_path(shift)' $0)")"
. "${ROOT_DIR}/../utils"

if [[ "$#" -gt "0" ]]; then
    print_err "Too many arguments"
    exit 1
fi

#-----------------------------------------------------------------------------
# Check for the existence of a container
RES_PS="$(docker ps -a --filter=name=sr-docker --format "{{.Status}}" 2>&1)"
if [[ "$?" != "0" ]]; then
    print_err "Issue running following command:"
    print_err "    docker ps -a --filter=name=sr-docker"
    print_err "                 --format \"{{.Status}}\""
    print_stdout "$RES_PS"
    exit 1
fi

if [[ -z "$RES_PS" ]]; then
    print_err "Container sr-docker is not created. Are you looking for:"
    print_err ""
    print_err "    sr-cli create"
    print_err ""
    exit 1
fi

#-----------------------------------------------------------------------------
# Run bash in sr-docker
docker exec -it -u serial sr-docker "/bin/bash"

