#!/usr/bin/env bash

#-----------------------------------------------------------------------------
ROOT_DIR="$(dirname "$(perl -e 'use Cwd "abs_path"; \
                                print abs_path(shift)' $0)")"
. "${ROOT_DIR}/../utils"

if [[ "$#" -gt "0" ]]; then
    print_err "Too many arguments"
    exit 1
fi

#-----------------------------------------------------------------------------
# Safety confirmation
IMAGE_NAME=${SR_IMAGE_NAME:-cyrillg/sr-dev}
print_war_q "Are you sure you want to delete the sr-docker container? (y/n) "
read RESP
if [[ "$RESP" != "y" ]]; then
    print_info "Cancelled"
    exit 1
fi

#-----------------------------------------------------------------------------
# Check for the existence of a container
RES_PS="$(docker ps -a --filter=name=sr-docker --format \"{{.ID}}\" 2>&1)"
if [[ "$?" != "0" ]]; then
    print_err "Issue running following command:"
    print_err "    docker ps -a --filter=name=sr-docker"
    print_err "                 --format \"{{.ID}}\""
    print_stdout "$RES_PS"
    exit 1
fi

if [[ -z "$RES_PS" ]]; then
    print_err "Container sr-docker is not created. Are you looking for:"
    print_err ""
    print_err "    sr-cli create"
    print_err ""
    exit 1
fi

#-----------------------------------------------------------------------------
# Delete the current container
print_info "Deleting sr-docker container..."
RES_RM="$(docker rm sr-docker 2>&1)"
if [[ "$?" != "0" ]]; then
    print_err "Could not delete the sr-docker container, please ensure it is not running:"
    print_err ""
    print_err "    sr-cli status / sr-cli stop"
    print_err ""
    print_stdout "$RES_RM"
    exit 1
fi
print_ok "Successfully deleted: sr-docker"

