#!/usr/bin/env bash

ROOT_DIR="$(dirname "$(perl -e 'use Cwd "abs_path"; \
                                print abs_path(shift)' $0)")"
. "${ROOT_DIR}/../utils"

if [ $# == 0 ]; then
    exit 3
fi

APP_DIR=`pwd`

if [[ -f "$APP_DIR/.bash_cli" ]]; then
    APP_DIR=`dirname "$APP_DIR"`
fi

if [[ ! -f "$APP_DIR/app/.bash_cli" ]]; then
    >&2 echo -e "\033[31mYou are not within a Bash CLI project\033[39m"
    >&2 echo "Please change your directory to a valid project or run the init command to set one up."
    exit 1
fi

NAME="$1"
FOLDER="${2-"/usr/bin"}"

# Setup symlink to cli script
ln -s "$APP_DIR/cli" "$FOLDER/$NAME"

# Setup autocompletion
cat > "/etc/bash_completion.d/$NAME" <<EOC
source "$APP_DIR/complete"
complete -F _bash_cli $NAME
EOC

# Setup setup.bash
if [[ -f ~/.bashrc ]]; then
    print_war_q "Automatically add the sourcing of setup.bash to your .bashrc? (y/n) "
    read RES
    if [[ "$RES" == "y" ]]; then
        REPO_DIR="$(cd ${ROOT_DIR}/.. && pwd)"
        echo "source ${REPO_DIR}/setup.bash" >> ~/.bashrc
        print_ok "Done"
    fi
fi

print_ok "Successfully installed ${NAME}"

